name: Test Project

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository code
        uses: actions/checkout@v3

      - name: Install Java JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 1.17

      - name: Build with Gradle
        run: ./gradlew build

      - name: Test with Gradle
        run: ./gradlew test
